# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'techteddy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for techteddy
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  target 'techteddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
